[package]
name = "bevy_app_compute"
version = "0.10.2"
authors = ["Kjolnyr <kjolnyr@protonmail.com>"]
edition = "2021"
description = "App compute plugin for Bevy"
repository = "https://github.com/Kjolnyr/bevy_app_compute"
homepage = "https://github.com/Kjolnyr/bevy_app_compute"
documentation = "https://docs.rs/bevy_app_compute"
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["game-development"]


[dependencies]
bevy = "0.10"
parking_lot = "0.12.1"
wgpu = "0.15.1"
codespan-reporting = "0.11.1"
futures-lite = "1.13.0"

[[example]]
name = "simple"

[[example]]
name = "multi_pass"

[[example]]
name = "one_shot"